### ISSUE TITLE
Error when watching/building folder

### ISSUE THREAD

**Issue by brylie** [francoislaberge/diagrams#4]
When telling diagrams to watch/build a folder, I am getting the following error:

```sh
$ diagrams watch --build .
Error: Provided directory does not exist
```

When using `diagrams watch .`, I get the following error:

```js
$ diagrams watch .
module.js:471
    throw err;
    ^

Error: Cannot find module 'chokidar'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/diagrams/bin/diagrams-watch.js:35:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

# Environment
- OS: Ubuntu 16.10
- Shell: bash

**Comment by francoislaberge** [comment]
Are you still getting this?

**Comment by francoislaberge** [comment]
Closing this, please reopen or comment if you are still experiencing this. Still works for me.
